[package]
name = "rust-dicegen"
version = "0.1.0"
authors = ["Vivek Parekh <vp@vivekparekh.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.7.3"
nom = "^5.1.1"